[feat]API_keyの取得方法説明モーダルの作成
takumi0616/gpt-logprobs pull request #59
Opened 2024-08-27 07:44 UTC by mtureit

# 対応 Issue
- resolve #57 

# 概要
APIキー取得の案内や入力を促すモーダルを実装

# 実装内容
1. FirstModalの作成
- 見た目だけで機能は作っていないです。
- APIキーの入力が行われない場合にアラートを表示します。
- APIキーの取得方法を見る」リンクをクリックすると、SecondModalに遷移します。
2. SecondeModalの作成
- APIキーの取得手順の最初のステップ（OpenAIアカウントの作成・ログイン）を案内するモーダルを作成しました。
-  画像に関してはダミー画像を入れています。
- 「APIキーの入力に戻る。」を押すとFirstModalに遷移するように作成
3. ThirdModalの作成
- デザインがなかったため、SecondModalのデザインを踏襲し、Figmaにあった文章を挿入しています。
- APIキーの取得手順の次のステップ（支払い情報の登録）を案内するモーダルを作成しました。
4. FourthModalの作成
- デザインがなかったため、SecondModalのデザインを踏襲し、Figmaにあった文章を挿入しています。
- APIキーの取得手順の次のステップ（APIキーの取得）を案内するモーダルを作成しました。
5.ChatInterfaceのindex.tsx の変更
- Modalの状態を保管、遷移させるための関数を作成しました。

補足
- すべてのモーダルに共通して、モーダルを閉じるボタンが配置しました。
- ボタンの色やhover時の効果を設定しました。

# 画面スクリーンショット等
FirstModal
![スクリーンショット 2024-08-27 160436](https://github.com/user-attachments/assets/c516c733-9f9f-4067-a84c-44e853ce2dc6)
SecondModal
![スクリーンショット 2024-08-27 160459](https://github.com/user-attachments/assets/42e6f95a-1053-4c44-abf4-c7168310839c)
ThirdModal
![スクリーンショット 2024-08-27 160516](https://github.com/user-attachments/assets/a977cdde-59e1-455a-a97d-eb1f9f0f335e)
FourthModal
![スクリーンショット 2024-08-27 160526](https://github.com/user-attachments/assets/a7020560-7741-41bb-80c3-1fa31f2a8d68)

# テスト項目
- [ ] ページを開くと説明モーダルが確認できる。
- [ ] modal間の画面遷移が確認できる。

# 備考

2024-08-27 09:11 UTC, TkymHrt requested changes
動作確認しました！
APIキー未入力防止のためにアラートメッセージを追加している点、とても良いですね。
***
いくつか気になった点をお伝えします。

- 同じCSSを適用する説明用のモーダルが3つ作成されていますが、名前が異なるだけで内容が重複しています。
- imgタグを使用していますが、Next.jsではパフォーマンスに影響が出る可能性があります。
- CSSの命名規則が統一されていない箇所があります（例: modalintro）。
***
これらの点を修正することで、よりシンプルかつ効率的にできると思います。

- 重複しているCSSを共通の/common内にModalコンポーネントとしてまとめ、再利用できるようにする。
- 画像の最適化のために、Next.jsのnext/imageのImageコンポーネントを使用する。また、画像ファイルはNext.jsプロジェクトのpublicフォルダに配置することで、パスが簡潔になります。
- 手順を説明するためのデータをオブジェクトにまとめ、ステップごとに切り替えられるようにする。
- プロジェクト全体でCSSのキャメルケースで命名規則を統一する。
以下に参考として簡単なコード例を示します。

```ts
const InstructionModal = ({ onClose }) => {
  const [currentStep, setCurrentStep] = useState(0);
  const steps = [
    { title: 'Open AI社のアカウントを作成・ログインする', content: 'Open AI社のAPIページにアクセスし、「Start building」をクリックしてください。', image: '/path-to-image1.png' },
    // 手順の数だけ追加していく感じです。
  ];

  return (
    <Modal>
      <h2>{steps[currentStep].title}</h2>
      <p>{steps[currentStep].content}</p>
      <Image src={steps[currentStep].image} alt={`Step ${currentStep + 1}`} fill />
      <button onClick={() => setCurrentStep(prev => prev - 1)} disabled={currentStep === 0}>戻る</button>
      <button onClick={() => setCurrentStep(prev => prev + 1)} disabled={currentStep === steps.length - 1}>次へ</button>
      <button onClick={onClose}>閉じる</button>
    </Modal>
  );
};

export default InstructionModal;
```
***
**また、Figmaには数ページ分のデザイン例を作成していますが、全ページ分つくる予定は無いので、画像のスクリーンショット追加や解説文を調べつつ追加していただけると助かります！**
(APIキーの入力確定時にはキーが更新される仕組みもできれば・・・|ω･)ﾁﾗ )

<br>

2024-08-29 08:31 UTC, mtureit commented
編集箇所が膨大になったため一度pushいたします。
現在の進行状況として
- 重複しているCSSを共通の/common内にModalコンポーネントとしてまとめ、再利用できるようにする。
- 画像の最適化のために、Next.jsのnext/imageのImageコンポーネントを使用する。
- 手順を説明するためのデータをまとめ、ステップごとに切り替えられるようにする。
を行いました。 
6ステップで説明書モーダルを作成しました。
**APIキーの入力確定時にはキーが更新される仕組み**は難航しておりまだできてないです...

### スクリーンショット
![スクリーンショット 2024-08-29 172238](https://github.com/user-attachments/assets/c2719091-c116-4190-98fe-eb27d40a84b1)
![スクリーンショット 2024-08-29 172343](https://github.com/user-attachments/assets/f399eb02-572e-4f84-804f-d8010c8650cf)
![スクリーンショット 2024-08-29 172348](https://github.com/user-attachments/assets/939dd69f-9b22-42d5-971e-0891b67d6f5b)
![スクリーンショット 2024-08-29 172353](https://github.com/user-attachments/assets/0355f319-e450-44a5-ad72-cc12d224f412)
![スクリーンショット 2024-08-29 172358](https://github.com/user-attachments/assets/d860e7a3-2749-418f-bee4-a1fcdb42b1c6)
![スクリーンショット 2024-08-29 172406](https://github.com/user-attachments/assets/bfed354e-e10e-4729-becf-b1ac34448885)
![スクリーンショット 2024-08-29 172413](https://github.com/user-attachments/assets/067586b4-42e3-479a-a376-0f0ec59e2873)

2024-08-31 16:23 UTC, TkymHrt reviewed
動作が完璧で、大変素晴らしいです！コンポーネント化が進み、非常に効率的なコードになっていると思います。


Figmaのデザインを参考に修正してみたところ、いくつか改善点が見つかりました。以下に例を記載しておきます。画像では既にフォントを変更していますが、このPRマージ後に変更します。（ここはこうした方が良いなど、感じたところがあればSlackでメッセージください！）


また、コメントをつけていますが、CSSやファイル名の命名統一、適当なアイコンの適用をお願いします。

`FirstModal.module.css`
```css
.firstmodalOverlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
  font-weight: bold;
}

.firstmodalContent {
  background-color: #ffffff;
  border-radius: 15px;
  padding: 40px;
  width: 500px;
  max-width: 90%;
  text-align: center;
  position: relative;
}

.closeButton {
  position: absolute;
  top: 18px;
  right: 18px;
  background: none;
  border: none;
  font-size: 25px;
  cursor: pointer;
  color: #7b90a6;
}

.title {
  font-size: 24px;
  margin-bottom: 10px;
  font-weight: bold;
  color: #333;
}

.description {
  text-align: left;
  font-size: 14px;
  margin-bottom: 20px;
  color: #2c3844;
  font-weight: normal;
}

.apititle {
  text-align: left;
  font-size: 20px;
  color: #333;
  margin-bottom: 10px;
}

.input {
  width: 100%;
  padding: 10px 20px;
  font-weight: normal;
  border-radius: 8px;
  border: 2px solid #b6c5d5;
  font-size: 16px;
  margin-bottom: 20px;
  outline: none;
  box-shadow: none;
}

.outbox {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.link {
  font-size: 14px;
  color: #007bff;
  cursor: pointer;
  display: flex;
  align-items: center;
  transition: color 0.3s; /* 色の変化を滑らかにする */
}

.link:hover {
  color: #80bfff; /* 色を薄くする */
}

.startButton {
  padding: 12px 24px;
  background-color: #333333;
  color: #f0f7ff;
  border: none;
  border-radius: 8px;
  font-size: 16px;
  cursor: pointer;
  width: 140px;
  display: flex;
  justify-content: center;
  align-items: center;
}

.startButton:hover {
  transition:
    background-color 0.3s,
    color 0.3s,
    border-color 0.3s;
  background-color: #a6a6a6;
}
```

`InstructionModal.module.css`
```css
.modalOverlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
  font-weight: bold;
}

.modalContent {
  background-color: #ffffff;
  border-radius: 15px;
  padding: 40px;
  width: 500px;
  max-width: 90%;
  text-align: center;
  position: relative;
}

.closeButton {
  position: absolute;
  top: 18px;
  right: 18px;
  background: none;
  border: none;
  font-size: 25px;
  cursor: pointer;
  color: #7b90a6;
}

.title {
  font-size: 19px;
  margin-bottom: 20px;
  font-weight: bold;
  color: #333;
}

.modalIntro {
  border: 1px solid #ccc;
  border-radius: 10px;
  padding: 20px;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  margin-bottom: 20px;
  text-align: left;
}

.step {
  font-size: 14px;
  color: #666;
  margin-bottom: 10px;
  text-align: left;
}

.subtitle {
  display: flex;
  align-items: flex-start;
  text-wrap: wrap;
  font-size: 20px;
  color: #333;
  margin-bottom: 10px;
}

.icon {
  margin: 2px 8px 0 0;
  width: 24px;
  height: 24px;
  flex-shrink: 0;
  color: #3b82f6;
}

.subtitleText {
  display: inline-block;
}

.description {
  font-size: 14px;
  font-weight: normal;
  margin-bottom: 20px;
  color: #333;
}

.image {
  width: 100%;
  height: auto;
  margin-bottom: 20px;
}

.imageRounded {
  border-radius: 12px;
}

.navigation {
  display: flex;
  justify-content: flex-end;
  gap: 10px;
  margin-top: 20px;
}

.backButton,
.nextButton {
  padding: 10px 20px;
  border-radius: 8px;
  border: none;
  cursor: pointer;
}

.backButton:hover,
.nextButton:hover {
  background-color: #f0f0f0;
  color: #666;
  border-color: #666;
  transition:
    background-color 0.3s,
    color 0.3s,
    border-color 0.3s;
}

.backButton {
  background-color: #ffffff;
  color: #333;
  border: 2px solid #333;
}

.nextButton {
  background-color: #ffffff;
  color: #333;
  border: 2px solid #333;
}

.disabledButton {
  cursor: not-allowed;
  opacity: 0.5;
}

.backFirstBox {
  margin-top: 20px;
  text-align: right;
}

.backFirstText {
  font-size: 14px;
  cursor: pointer;
  transition: color 0.3s ease;
  display: inline-block;
}

.backFirstText:hover {
  color: #666;
}

```
修正後 ↓
|![image](https://github.com/user-attachments/assets/3c89829d-e28c-4dcf-a29e-87827ccda4d7)|![image](https://github.com/user-attachments/assets/b9d9647c-af17-44d5-89c0-e88039510b12)|
|--|--|

2024-08-31 16:23 UTC, TkymHrt commented on app/components/modal/FirstModal/FirstModal.module.css
> +.firstmodalOverlay {
[キャメルケース](https://developer.mozilla.org/ja/docs/Glossary/Camel_case)に統一でお願いします！
```suggestion
.firstModalOverlay {
```

2024-08-31 16:23 UTC, TkymHrt commented on app/components/modal/FirstModal/FirstModal.module.css
> +.firstmodalContent {
[キャメルケース](https://developer.mozilla.org/ja/docs/Glossary/Camel_case)に統一でお願いします！
```suggestion
.firstModalContent {
```

2024-08-31 16:23 UTC, TkymHrt commented on app/components/modal/FirstModal/FirstModal.module.css
> +.apititle {
[キャメルケース](https://developer.mozilla.org/ja/docs/Glossary/Camel_case)に統一でお願いします！
```suggestion
.apiTitle {
```

2024-08-31 16:23 UTC, TkymHrt commented on public/FifthModalview.png
画像名全て[キャメルケース](https://developer.mozilla.org/ja/docs/Glossary/Camel_case)に統一するか(viewのvが小文字)、下記サイトを参考に良い感じに修正してほしいです。

[もうページで分けない！　画像ファイルの命名規則](https://webnaut.jp/technology/20210910-3953/)

2024-08-31 16:23 UTC, TkymHrt commented on app/components/modal/InstructionModal/InstructionModal.tsx
> +    icon: <Bs1Circle className={styles.icon} />, // ステップ1のアイコン
Figmaで使用しているアイコンにしてほしいです！（6番まで）
```suggestion
    icon: <TbCircleNumber1Filled className={styles.icon} />, // ステップ1のアイコン
```

2024-08-31 16:23 UTC, TkymHrt commented on app/components/modal/InstructionModal/InstructionModal.tsx
> +          &times;
React Iconsにちょうどよいのがあります！
他のモーダルでも直せるとよいですね。
```suggestion
          <RxCross1 />
```

2024-09-02 15:06 UTC, TkymHrt approved these changes
![LGTM](https://storage.googleapis.com/lgtm-ea733.appspot.com/lgtm/8249585)

2024-09-02 15:07 UTC, merged